/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        "dm-sans": ["DM Sans", "sans-serif"],
        "eb-garamond": ["EB Garamond", "serif"],
        "source-code-pro": ["Source Code Pro", "monospace"],
        "share-tech": ["Share Tech", "sans-serif"],
        niconne: ["Niconne", "cursive"],
        "rubik-scribble": ["Rubik Scribble", "system-ui"],
        habibi: ["Habibi", "serif"],
        "anek-gurmukhi": ["Anek Gurmukhi", "sans-serif"],
        oswald: ["Oswald", "sans-serif"],
        "roboto-slab": ["Roboto Slab", "serif"],
        urbanist: ["Urbanist", "sans-serif"],
        "bree-serif": ["Bree Serif", "serif"],
        courgette: ["Courgette", "cursive"],
        "permanent-marker": ["Permanent Marker", "cursive"],
        helvetica: ["Helvetica", "Arial", "sans-serif"],
        avenir: ["Avenir", "Helvetica", "Arial", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        "josefin-sans": ["Josefin Sans", "sans-serif"],
        "roboto-flex": ["Roboto Flex", "sans-serif"],
        domine: ["Domine", "serif"],
        figtree: ["Figtree", "sans-serif"],
        "futura-condensed": ["Futura Condensed", "sans-serif"],
        "source-sans": ["Source Sans 3", "sans-serif"],
        solway: ["Solway", "serif"],
        "chelsea-market": ["Chelsea Market", "cursive"],
        tektur: ["Tektur", "sans-serif"],
        sriracha: ["Sriracha", "cursive"],
        doto: ["DotGothic16", "sans-serif"],
        "bowlby-one-sc": ["Bowlby One SC", "cursive"],
        "protest-revolution": ["Protest Revolution", "sans-serif"],
        outfit: ["Outfit", "sans-serif"],
      },
    },
  },
  plugins: [],
};
